-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 11:48:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mycinemadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycinemadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycinemadb` DEFAULT CHARACTER SET utf8 ;
USE `mycinemadb` ;

-- -----------------------------------------------------
-- Table `mycinemadb`.`ADRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`ADRESA` (
  `IdAdresa` INT NOT NULL AUTO_INCREMENT,
  `Drzava` VARCHAR(45) NOT NULL,
  `Grad` VARCHAR(45) NOT NULL,
  `PostanskiBroj` VARCHAR(15) NULL,
  `Ulica` VARCHAR(45) NULL,
  `Broj` VARCHAR(6) NULL,
  PRIMARY KEY (`IdAdresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`KINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`KINO` (
  `Idkino` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NOT NULL,
  `ADRESA_IdAdresa` INT NOT NULL,
  PRIMARY KEY (`Idkino`),
  INDEX `fk_KINO_ADRESA_idx` (`ADRESA_IdAdresa` ASC) VISIBLE,
  CONSTRAINT `fk_KINO_ADRESA`
    FOREIGN KEY (`ADRESA_IdAdresa`)
    REFERENCES `mycinemadb`.`ADRESA` (`IdAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`ZAPOSLENI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`ZAPOSLENI` (
  `IdZaposleni` INT NOT NULL AUTO_INCREMENT,
  `JMB` CHAR(13) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Plata` DECIMAL(6,2) NULL,
  `KINO_Idkino` INT NOT NULL,
  `ADRESA_IdAdresa` INT NOT NULL,
  PRIMARY KEY (`IdZaposleni`),
  INDEX `fk_ZAPOSLENI_KINO1_idx` (`KINO_Idkino` ASC) VISIBLE,
  INDEX `fk_ZAPOSLENI_ADRESA1_idx` (`ADRESA_IdAdresa` ASC) VISIBLE,
  UNIQUE INDEX `JMB_UNIQUE` (`JMB` ASC) VISIBLE,
  CONSTRAINT `fk_ZAPOSLENI_KINO1`
    FOREIGN KEY (`KINO_Idkino`)
    REFERENCES `mycinemadb`.`KINO` (`Idkino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZAPOSLENI_ADRESA1`
    FOREIGN KEY (`ADRESA_IdAdresa`)
    REFERENCES `mycinemadb`.`ADRESA` (`IdAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`TELEFON_ZAPOSLENI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`TELEFON_ZAPOSLENI` (
  `Telefon` VARCHAR(20) NOT NULL,
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`Telefon`, `ZAPOSLENI_IdZaposleni`),
  INDEX `fk_TELEFON_ZAPOSLENI1_idx` (`ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`DOBAVLJAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`DOBAVLJAC` (
  `IdDobavljac` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NOT NULL,
  `ADRESA_IdAdresa` INT NOT NULL,
  PRIMARY KEY (`IdDobavljac`),
  INDEX `fk_DOBAVLJAC_ADRESA1_idx` (`ADRESA_IdAdresa` ASC) VISIBLE,
  CONSTRAINT `fk_DOBAVLJAC_ADRESA1`
    FOREIGN KEY (`ADRESA_IdAdresa`)
    REFERENCES `mycinemadb`.`ADRESA` (`IdAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`BANKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`BANKA` (
  `IdBanka` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NOT NULL,
  `ADRESA_IdAdresa` INT NOT NULL,
  PRIMARY KEY (`IdBanka`),
  INDEX `fk_BANKA_ADRESA1_idx` (`ADRESA_IdAdresa` ASC) VISIBLE,
  CONSTRAINT `fk_BANKA_ADRESA1`
    FOREIGN KEY (`ADRESA_IdAdresa`)
    REFERENCES `mycinemadb`.`ADRESA` (`IdAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`RACUN_U_BANCI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`RACUN_U_BANCI` (
  `BrojRacuna` VARCHAR(45) NOT NULL,
  `DOBAVLJAC_IdDobavljac` INT NULL,
  `BANKA_IdBanke` INT NOT NULL,
  `KINO_Idkino` INT NULL,
  INDEX `fk_RACUN_U_BANCI_DOBAVLJAC1_idx` (`DOBAVLJAC_IdDobavljac` ASC) VISIBLE,
  INDEX `fk_RACUN_U_BANCI_BANKA1_idx` (`BANKA_IdBanke` ASC) VISIBLE,
  INDEX `fk_RACUN_U_BANCI_KINO1_idx` (`KINO_Idkino` ASC) VISIBLE,
  PRIMARY KEY (`BrojRacuna`),
  CONSTRAINT `fk_RACUN_U_BANCI_DOBAVLJAC1`
    FOREIGN KEY (`DOBAVLJAC_IdDobavljac`)
    REFERENCES `mycinemadb`.`DOBAVLJAC` (`IdDobavljac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RACUN_U_BANCI_BANKA1`
    FOREIGN KEY (`BANKA_IdBanke`)
    REFERENCES `mycinemadb`.`BANKA` (`IdBanka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RACUN_U_BANCI_KINO1`
    FOREIGN KEY (`KINO_Idkino`)
    REFERENCES `mycinemadb`.`KINO` (`Idkino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`MENADZER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`MENADZER` (
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`ZAPOSLENI_IdZaposleni`),
  CONSTRAINT `fk_MENADZER_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`UGOVOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`UGOVOR` (
  `IdUgovor` INT NOT NULL AUTO_INCREMENT,
  `PocetakRadnogOdnosa` DATETIME NULL,
  `PrekidUgovora` DATETIME NULL,
  `MENADZER_ZAPOSLENI_IdZaposleni` INT NOT NULL,
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`IdUgovor`),
  INDEX `fk_UGOVOR_MENADZER1_idx` (`MENADZER_ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  INDEX `fk_UGOVOR_ZAPOSLENI1_idx` (`ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  CONSTRAINT `fk_UGOVOR_MENADZER1`
    FOREIGN KEY (`MENADZER_ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`MENADZER` (`ZAPOSLENI_IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UGOVOR_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`KORISNICKI_NALOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`KORISNICKI_NALOG` (
  `IdKorisnickiNalog` INT NOT NULL AUTO_INCREMENT,
  `KorisnickoIme` VARCHAR(55) NOT NULL,
  `Lozinka` VARCHAR(55) NOT NULL,
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`IdKorisnickiNalog`),
  UNIQUE INDEX `KorisnickoIme_UNIQUE` (`KorisnickoIme` ASC) VISIBLE,
  INDEX `fk_KORISNICKI_NALOG_ZAPOSLENI1_idx` (`ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  CONSTRAINT `fk_KORISNICKI_NALOG_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`SALA` (
  `IdSala` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(8) NOT NULL,
  `Tip` VARCHAR(5) NOT NULL,
  `KINO_Idkino` INT NOT NULL,
  PRIMARY KEY (`IdSala`),
  INDEX `fk_SALA_KINO1_idx` (`KINO_Idkino` ASC) VISIBLE,
  CONSTRAINT `fk_SALA_KINO1`
    FOREIGN KEY (`KINO_Idkino`)
    REFERENCES `mycinemadb`.`KINO` (`Idkino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`RED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`RED` (
  `BrojReda` INT NOT NULL,
  `SALA_IdSala` INT NOT NULL,
  PRIMARY KEY (`BrojReda`, `SALA_IdSala`),
  INDEX `fk_RED_SALA1_idx` (`SALA_IdSala` ASC) VISIBLE,
  CONSTRAINT `fk_RED_SALA1`
    FOREIGN KEY (`SALA_IdSala`)
    REFERENCES `mycinemadb`.`SALA` (`IdSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`SJEDISTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`SJEDISTE` (
  `BrojSjedista` INT NOT NULL,
  `RED_IdRed` INT NOT NULL,
  `RED_SALA_IdSala` INT NOT NULL,
  PRIMARY KEY (`BrojSjedista`, `RED_IdRed`, `RED_SALA_IdSala`),
  INDEX `fk_SJEDISTE_RED1_idx` (`RED_IdRed` ASC, `RED_SALA_IdSala` ASC) VISIBLE,
  CONSTRAINT `fk_SJEDISTE_RED1`
    FOREIGN KEY (`RED_IdRed` , `RED_SALA_IdSala`)
    REFERENCES `mycinemadb`.`RED` (`BrojReda` , `SALA_IdSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`RECEPCIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`RECEPCIONER` (
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`ZAPOSLENI_IdZaposleni`),
  CONSTRAINT `fk_RECEPCIONER_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`FILM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`FILM` (
  `IdFilm` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(155) NOT NULL,
  `KratakOpis` VARCHAR(1500) NULL,
  `Trajanje` INT NULL,
  PRIMARY KEY (`IdFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`PROJEKCIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`PROJEKCIJA` (
  `SALA_IdSala` INT NOT NULL,
  `DatumIVrijemePrikazivanja` DATETIME NOT NULL,
  `FILM_IdFilm` INT NOT NULL,
  `Cijena` DECIMAL(4,2) NULL,
  PRIMARY KEY (`SALA_IdSala`, `FILM_IdFilm`, `DatumIVrijemePrikazivanja`),
  INDEX `fk_SALA_has_PROJEKCIJA_SALA1_idx` (`SALA_IdSala` ASC) VISIBLE,
  INDEX `fk_PROJEKCIJA_FILM1_idx` (`FILM_IdFilm` ASC) VISIBLE,
  CONSTRAINT `fk_SALA_has_PROJEKCIJA_SALA1`
    FOREIGN KEY (`SALA_IdSala`)
    REFERENCES `mycinemadb`.`SALA` (`IdSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROJEKCIJA_FILM1`
    FOREIGN KEY (`FILM_IdFilm`)
    REFERENCES `mycinemadb`.`FILM` (`IdFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`KARTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`KARTA` (
  `IdKarta` INT NOT NULL AUTO_INCREMENT,
  `DatumIVrijemeIzdavanja` DATETIME NULL,
  `RECEPCIONER_ZAPOSLENI_IdZaposleni` INT NOT NULL,
  `PROJEKCIJA_SALA_IdSala` INT NOT NULL,
  `PROJEKCIJA_FILM_IdFilm` INT NOT NULL,
  `PROJEKCIJA_DatumIVrijemePrikazivanja` DATETIME NOT NULL,
  `SJEDISTE_BrojSjedista` INT NOT NULL,
  `SJEDISTE_RED_IdRed` INT NOT NULL,
  PRIMARY KEY (`IdKarta`),
  INDEX `fk_KARTA_RECEPCIONER1_idx` (`RECEPCIONER_ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  INDEX `fk_KARTA_PROJEKCIJA1_idx` (`PROJEKCIJA_SALA_IdSala` ASC, `PROJEKCIJA_FILM_IdFilm` ASC, `PROJEKCIJA_DatumIVrijemePrikazivanja` ASC) VISIBLE,
  INDEX `fk_KARTA_SJEDISTE1_idx` (`SJEDISTE_BrojSjedista` ASC, `SJEDISTE_RED_IdRed` ASC) VISIBLE,
  CONSTRAINT `fk_KARTA_RECEPCIONER1`
    FOREIGN KEY (`RECEPCIONER_ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`RECEPCIONER` (`ZAPOSLENI_IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KARTA_PROJEKCIJA1`
    FOREIGN KEY (`PROJEKCIJA_SALA_IdSala` , `PROJEKCIJA_FILM_IdFilm` , `PROJEKCIJA_DatumIVrijemePrikazivanja`)
    REFERENCES `mycinemadb`.`PROJEKCIJA` (`SALA_IdSala` , `FILM_IdFilm` , `DatumIVrijemePrikazivanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KARTA_SJEDISTE1`
    FOREIGN KEY (`SJEDISTE_BrojSjedista` , `SJEDISTE_RED_IdRed`)
    REFERENCES `mycinemadb`.`SJEDISTE` (`BrojSjedista` , `RED_IdRed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`ZANR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`ZANR` (
  `IdZanr` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(155) NULL,
  PRIMARY KEY (`IdZanr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`FILM_ZANR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`FILM_ZANR` (
  `ZANR_IdZanr` INT NOT NULL,
  `FILM_IdFilm` INT NOT NULL,
  PRIMARY KEY (`ZANR_IdZanr`, `FILM_IdFilm`),
  INDEX `fk_ZANR_has_PROJEKCIJA_ZANR1_idx` (`ZANR_IdZanr` ASC) VISIBLE,
  INDEX `fk_FILM_ZANR_FILM1_idx` (`FILM_IdFilm` ASC) VISIBLE,
  CONSTRAINT `fk_ZANR_has_PROJEKCIJA_ZANR1`
    FOREIGN KEY (`ZANR_IdZanr`)
    REFERENCES `mycinemadb`.`ZANR` (`IdZanr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FILM_ZANR_FILM1`
    FOREIGN KEY (`FILM_IdFilm`)
    REFERENCES `mycinemadb`.`FILM` (`IdFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`LICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`LICE` (
  `IdLice` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(55) NULL,
  `Prezime` VARCHAR(55) NULL,
  PRIMARY KEY (`IdLice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`VRSTA_ANGAZMANA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`VRSTA_ANGAZMANA` (
  `IdVrstaAngazmana` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(55) NULL,
  PRIMARY KEY (`IdVrstaAngazmana`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`ANGAZMAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`ANGAZMAN` (
  `LICE_IdLica` INT NOT NULL,
  `VRSTA_ANGAZMANA_IdVrstaAngazmana` INT NOT NULL,
  `FILM_IdFilm` INT NOT NULL,
  PRIMARY KEY (`LICE_IdLica`, `VRSTA_ANGAZMANA_IdVrstaAngazmana`, `FILM_IdFilm`),
  INDEX `fk_ANGAZMAN_LICE1_idx` (`LICE_IdLica` ASC) VISIBLE,
  INDEX `fk_ANGAZMAN_VRSTA_ANGAZMANA1_idx` (`VRSTA_ANGAZMANA_IdVrstaAngazmana` ASC) VISIBLE,
  INDEX `fk_ANGAZMAN_FILM1_idx` (`FILM_IdFilm` ASC) VISIBLE,
  CONSTRAINT `fk_ANGAZMAN_LICE1`
    FOREIGN KEY (`LICE_IdLica`)
    REFERENCES `mycinemadb`.`LICE` (`IdLice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANGAZMAN_VRSTA_ANGAZMANA1`
    FOREIGN KEY (`VRSTA_ANGAZMANA_IdVrstaAngazmana`)
    REFERENCES `mycinemadb`.`VRSTA_ANGAZMANA` (`IdVrstaAngazmana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANGAZMAN_FILM1`
    FOREIGN KEY (`FILM_IdFilm`)
    REFERENCES `mycinemadb`.`FILM` (`IdFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`RACUN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`RACUN` (
  `IdRacun` INT NOT NULL AUTO_INCREMENT,
  `DatumIVrijemeIzdavanja` DATETIME NULL,
  `RECEPCIONER_ZAPOSLENI_IdZaposleni` INT NOT NULL,
  PRIMARY KEY (`IdRacun`),
  INDEX `fk_RACUN_RECEPCIONER1_idx` (`RECEPCIONER_ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  CONSTRAINT `fk_RACUN_RECEPCIONER1`
    FOREIGN KEY (`RECEPCIONER_ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`RECEPCIONER` (`ZAPOSLENI_IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`KATEGORIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`KATEGORIJA` (
  `IdKategorija` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NULL,
  PRIMARY KEY (`IdKategorija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`PROIZVOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`PROIZVOD` (
  `IdProizvod` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NULL,
  `Cijena` DECIMAL(4,2) NULL,
  `KATEGORIJA_IdKategorija` INT NOT NULL,
  PRIMARY KEY (`IdProizvod`),
  INDEX `fk_PROIZVOD_KATEGORIJA1_idx` (`KATEGORIJA_IdKategorija` ASC) VISIBLE,
  CONSTRAINT `fk_PROIZVOD_KATEGORIJA1`
    FOREIGN KEY (`KATEGORIJA_IdKategorija`)
    REFERENCES `mycinemadb`.`KATEGORIJA` (`IdKategorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`STAVKA_RACUNA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`STAVKA_RACUNA` (
  `Kolicina` INT NULL,
  `RACUN_IdRacun` INT NOT NULL,
  `PROIZVOD_IdProizvod` INT NOT NULL,
  PRIMARY KEY (`RACUN_IdRacun`, `PROIZVOD_IdProizvod`),
  INDEX `fk_STAVKA_RACUNA_RACUN1_idx` (`RACUN_IdRacun` ASC) VISIBLE,
  INDEX `fk_STAVKA_RACUNA_PROIZVOD1_idx` (`PROIZVOD_IdProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_STAVKA_RACUNA_RACUN1`
    FOREIGN KEY (`RACUN_IdRacun`)
    REFERENCES `mycinemadb`.`RACUN` (`IdRacun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAVKA_RACUNA_PROIZVOD1`
    FOREIGN KEY (`PROIZVOD_IdProizvod`)
    REFERENCES `mycinemadb`.`PROIZVOD` (`IdProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`SKLADISTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`SKLADISTE` (
  `IdSkladiste` INT NOT NULL AUTO_INCREMENT,
  `NazivSkladiste` VARCHAR(45) NULL,
  PRIMARY KEY (`IdSkladiste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`MAGACIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`MAGACIONER` (
  `ZAPOSLENI_IdZaposleni` INT NOT NULL,
  `SKLADISTE_IdSkladista` INT NULL,
  PRIMARY KEY (`ZAPOSLENI_IdZaposleni`),
  INDEX `fk_MAGACIONER_SKLADISTE1_idx` (`SKLADISTE_IdSkladista` ASC) VISIBLE,
  CONSTRAINT `fk_MAGACIONER_ZAPOSLENI1`
    FOREIGN KEY (`ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`ZAPOSLENI` (`IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MAGACIONER_SKLADISTE1`
    FOREIGN KEY (`SKLADISTE_IdSkladista`)
    REFERENCES `mycinemadb`.`SKLADISTE` (`IdSkladiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`NARUDZBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`NARUDZBA` (
  `IdNarudzba` INT NOT NULL AUTO_INCREMENT,
  `DatumIVrijemeNarudzbe` DATETIME NULL,
  `MAGACIONER_ZAPOSLENI_IdZaposleni` INT NOT NULL,
  `DOBAVLJAC_IdDobavljac` INT NOT NULL,
  PRIMARY KEY (`IdNarudzba`),
  INDEX `fk_NARUDZBA_MAGACIONER1_idx` (`MAGACIONER_ZAPOSLENI_IdZaposleni` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_DOBAVLJAC1_idx` (`DOBAVLJAC_IdDobavljac` ASC) VISIBLE,
  CONSTRAINT `fk_NARUDZBA_MAGACIONER1`
    FOREIGN KEY (`MAGACIONER_ZAPOSLENI_IdZaposleni`)
    REFERENCES `mycinemadb`.`MAGACIONER` (`ZAPOSLENI_IdZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NARUDZBA_DOBAVLJAC1`
    FOREIGN KEY (`DOBAVLJAC_IdDobavljac`)
    REFERENCES `mycinemadb`.`DOBAVLJAC` (`IdDobavljac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`STAVKA_NARUDZBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`STAVKA_NARUDZBE` (
  `Kolicina` INT NULL,
  `NARUDZBA_IdNarudzba` INT NOT NULL,
  `PROIZVOD_IdProizvod` INT NOT NULL,
  PRIMARY KEY (`NARUDZBA_IdNarudzba`, `PROIZVOD_IdProizvod`),
  INDEX `fk_STAVKA_NARUDZBE_NARUDZBA1_idx` (`NARUDZBA_IdNarudzba` ASC) VISIBLE,
  INDEX `fk_STAVKA_NARUDZBE_PROIZVOD1_idx` (`PROIZVOD_IdProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_STAVKA_NARUDZBE_NARUDZBA1`
    FOREIGN KEY (`NARUDZBA_IdNarudzba`)
    REFERENCES `mycinemadb`.`NARUDZBA` (`IdNarudzba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAVKA_NARUDZBE_PROIZVOD1`
    FOREIGN KEY (`PROIZVOD_IdProizvod`)
    REFERENCES `mycinemadb`.`PROIZVOD` (`IdProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`FAKTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`FAKTURA` (
  `IdFaktura` INT NOT NULL AUTO_INCREMENT,
  `DatumIVrijemeIzdavanjaFakture` DATETIME NULL,
  `DOBAVLJAC_IdDobavljac` INT NOT NULL,
  PRIMARY KEY (`IdFaktura`),
  INDEX `fk_FAKTURA_DOBAVLJAC1_idx` (`DOBAVLJAC_IdDobavljac` ASC) VISIBLE,
  CONSTRAINT `fk_FAKTURA_DOBAVLJAC1`
    FOREIGN KEY (`DOBAVLJAC_IdDobavljac`)
    REFERENCES `mycinemadb`.`DOBAVLJAC` (`IdDobavljac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`STAVKA_FAKTURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`STAVKA_FAKTURE` (
  `FAKTURA_IdFaktura` INT NOT NULL,
  `PROIZVOD_IdProizvod` INT NOT NULL,
  `Kolicina` INT NULL,
  PRIMARY KEY (`FAKTURA_IdFaktura`, `PROIZVOD_IdProizvod`),
  INDEX `fk_STAVKA_FAKTURE_FAKTURA1_idx` (`FAKTURA_IdFaktura` ASC) VISIBLE,
  INDEX `fk_STAVKA_FAKTURE_PROIZVOD1_idx` (`PROIZVOD_IdProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_STAVKA_FAKTURE_FAKTURA1`
    FOREIGN KEY (`FAKTURA_IdFaktura`)
    REFERENCES `mycinemadb`.`FAKTURA` (`IdFaktura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAVKA_FAKTURE_PROIZVOD1`
    FOREIGN KEY (`PROIZVOD_IdProizvod`)
    REFERENCES `mycinemadb`.`PROIZVOD` (`IdProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`SKLADISTE_PROIZVOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`SKLADISTE_PROIZVOD` (
  `SKLADISTE_IdSkladiste` INT NOT NULL,
  `PROIZVOD_IdProizvod` INT NOT NULL,
  `KolicinaNaStanju` INT NULL,
  PRIMARY KEY (`SKLADISTE_IdSkladiste`, `PROIZVOD_IdProizvod`),
  INDEX `fk_SKLADISTE_has_PROIZVOD_PROIZVOD1_idx` (`PROIZVOD_IdProizvod` ASC) VISIBLE,
  INDEX `fk_SKLADISTE_has_PROIZVOD_SKLADISTE1_idx` (`SKLADISTE_IdSkladiste` ASC) VISIBLE,
  CONSTRAINT `fk_SKLADISTE_has_PROIZVOD_SKLADISTE1`
    FOREIGN KEY (`SKLADISTE_IdSkladiste`)
    REFERENCES `mycinemadb`.`SKLADISTE` (`IdSkladiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SKLADISTE_has_PROIZVOD_PROIZVOD1`
    FOREIGN KEY (`PROIZVOD_IdProizvod`)
    REFERENCES `mycinemadb`.`PROIZVOD` (`IdProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`TELEFON_KINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`TELEFON_KINO` (
  `Telefon` VARCHAR(20) NOT NULL,
  `KINO_Idkino` INT NOT NULL,
  PRIMARY KEY (`Telefon`, `KINO_Idkino`),
  INDEX `fk_TELEFON_KINO_KINO1_idx` (`KINO_Idkino` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_KINO_KINO1`
    FOREIGN KEY (`KINO_Idkino`)
    REFERENCES `mycinemadb`.`KINO` (`Idkino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`TELEFON_DOBAVLJAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`TELEFON_DOBAVLJAC` (
  `Telefon` VARCHAR(20) NOT NULL,
  `DOBAVLJAC_IdDobavljac` INT NOT NULL,
  PRIMARY KEY (`Telefon`, `DOBAVLJAC_IdDobavljac`),
  INDEX `fk_TELEFON_DOBAVLJAC_DOBAVLJAC1_idx` (`DOBAVLJAC_IdDobavljac` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_DOBAVLJAC_DOBAVLJAC1`
    FOREIGN KEY (`DOBAVLJAC_IdDobavljac`)
    REFERENCES `mycinemadb`.`DOBAVLJAC` (`IdDobavljac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycinemadb`.`TELEFON_BANKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycinemadb`.`TELEFON_BANKA` (
  `Telefon` VARCHAR(20) NOT NULL,
  `BANKA_IdBanka` INT NOT NULL,
  PRIMARY KEY (`Telefon`, `BANKA_IdBanka`),
  INDEX `fk_TELEFON_BANKA_BANKA1_idx` (`BANKA_IdBanka` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_BANKA_BANKA1`
    FOREIGN KEY (`BANKA_IdBanka`)
    REFERENCES `mycinemadb`.`BANKA` (`IdBanka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
